- name: deploye in EKS
  hosts:  production
  vars:
    image_version:  nginx
  tasks:
  - name: create deploy yaml template
    template:
      src:  deployment.j2
      dest: ./deployment_ready.yaml
  - name: Deploy the service
    k8s:
      state: present
      src:  deployment_ready.yaml
      namespace:  default
