- name: deploye in EKS
  hosts:  localhost
  vars:
    image_version:  "{{ image_id }}"
  tasks:
  - name: create deploy yaml template
    template:
      src:  deployment.j2
      dest: ./deployment_ready.yaml
  - name: Deploy the service
    community.kubernetes.k8s:
      state: present
      src:  deployment_ready.yaml
      namespace:  default
